# Site settings
title: San Francisco Human Services Agency
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "/hsa-docs" # the subpath of your site, e.g. /blog/
# url: "http://www.sfhsa.org/" # the base hostname & protocol for your site
# twitter_username: designincode
github_username:  exygy-design

# Build settings
markdown: kramdown
